### ISSUE TITLE
Error messages are not useful

### ISSUE THREAD

**Issue by Coarotbas** [MarkReedZ/mrjson#1]
If this was a large json file this may not be useful for figuring out the problem.  

```
>>> import mrjson
>>> mrjson.loads("tru")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: JSON_BAD_IDENTIFIER
```

**Comment by MarkReedZ** [comment]
Yeah this is on my todo list.  If you feel like it make a pull request and edit tests.py changing the expected value for the exception tests to what you think should be a good error message.  I'll modify the code to match the new tests.

**Comment by MarkReedZ** [comment]
I pulled in #3 and committed new error messages with a few changes.  Thanks for the suggestions and tests - it made it easy to just knock this out.
