### ISSUE TITLE
Negative infinity doesn't work

### ISSUE THREAD

**Issue by Coarotbas** [MarkReedZ/mrjson#2]
While looking at the tests I noticed this doesn't work and probably should?

```
>>> mrjson.loads("-Infinity")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: JSON_BAD_NUMBER;
```

**Comment by MarkReedZ** [comment]
I added a test for this and committed the fix with your pull request

https://github.com/MarkReedZ/mrjson/commit/fd6915409e1ca79efaa8bc20fa0b949610708e56
